### ISSUE TITLE
HTTPHandler is not defined

### ISSUE THREAD

**Issue by luis-rr** [NeuralEnsemble/NeuroTools#65]
I get an exception with latest NeuroTools if I have an environment variable HTTP_PROXY defined.
Repro steps:

``` shell
virtualenv --system-site-packages venv  # need site packages for numpy
venv/bin/pip install NeuroTools==0.3.1
venv/bin/python -c 'import NeuroTools.parameters.validators'
HTTP_PROXY='here' venv/bin/python -c 'import NeuroTools.parameters.validators'
```

Output:

``` python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/riquelme/dev/mesobuilder/venv/lib/python2.7/site-packages/NeuroTools/parameters/__init__.py", line 89, in <module>
    opener = build_opener(proxy_support, HTTPHandler)
NameError: name 'HTTPHandler' is not defined
```

This seems to be missing an import of some type. Independently of the solution, why does NeuroTool look at my environment variables to set up stuff? Specially something as generic as "HTTP_PROXY", this is very unexpected and may cause compatibility issues.

**Comment by sriniwaas** [comment]
Is this issue resolved ... me too getting the same error.

**Comment by laurentperrinet** [comment]
Hi!

thanks for you request. indeed, this repo is more a maintenance version, and concerning the particular cases of parameters, you will certainly find a more updated version @ https://github.com/NeuralEnsemble/parameters/

Cheers,
Laurent
